### ISSUE TITLE
Access request deprovisioning does not revoke app access

### ISSUE THREAD

**Issue by gwandwingor** [Axway/agents-apigee#122]
Hi,

Following a subscription suspension, an access request deprovisioning event is sent to the DA. 
However, the deprovisioning process doesn't remove access to the product in the Apigee app.

See agent logs below :

![MicrosoftTeams-image](https://github.com/Axway/agents-apigee/assets/22820414/3d8c5521-42e0-4801-bec5-108203eb7b48)

**Comment by jcollins-axway** [comment]
@gwandwingor the fix for this is in a pre-release build, `docker pull ghcr.io/axway/apigee_discovery_agent:v0.1.16-alpha1`. Please validate that it is fixed and comment back on this issue.

**Comment by gwandwingor** [comment]
Hi,
I was able to test this build of the agent and noticed that access request deprovisioning now removes the product access from the application.
I will do some more testing on monday before I close this ticket

**Comment by gwandwingor** [comment]
Hi,
After some more testing, it appears that deleting the product from the app credential can lead to the creation of "skeleton keys", that may pose a security risk.
Here's the excerpt from the apigee official documentation :
![image](https://github.com/Axway/agents-apigee/assets/22820414/de43350a-9f66-4679-8bbe-8c95b82ed1e9)
https://cloud.google.com/apigee/docs/api-platform/publish/creating-apps-surface-your-api

Furthermore, the Apigee UI doesn't seem to allow having Credentials without access to a product, as shown below.
![image](https://github.com/Axway/agents-apigee/assets/22820414/9abff754-f6dd-4a24-aaae-93f31fd5fba2)

It seems like the safest option would be to revoke access to the product from the app as shown below in the UI :
![image](https://github.com/Axway/agents-apigee/assets/22820414/2c5f6433-324b-46cd-882f-288a99a11f79)

This would effectively prevent from being able to query the API Proxy without generating skeleton keys.

**Comment by jcollins-axway** [comment]
@gwandwingor thanks for that information, I made additional changes to handle this situation. Please test out this version `docker pull ghcr.io/axway/apigee_discovery_agent:v0.1.16-alpha2`

**Comment by gwandwingor** [comment]
Hi @jcollins-axway,

I deployed the latest build but now I cannot create access requests anymore. I get the following error 
![image](https://github.com/Axway/agents-apigee/assets/22820414/8e3682fc-2f77-4df8-8296-8effb97e3f5b)

I can provide the full log where we can see the app creation as well as a screen recording of the whole test.
