### ISSUE TITLE
Proxy mode - Access request deprovisioning does not revoke product access

### ISSUE THREAD

**Issue by gwandwingor** [Axway/agents-apigee#140]
Hi,

In PROXY discovery mode, deprovisioning an access request doesn't revoke the product access. As can be seen from the log below, no error is thrown.
![image](https://github.com/Axway/agents-apigee/assets/22820414/f7a30eda-0a1a-4dce-af6f-c68e6baee53e)

However, after the process is finished, credential object is still linked to the API Product

![image](https://github.com/Axway/agents-apigee/assets/22820414/1e28954b-a892-438d-97d0-128548487d18)

Agent version is 0.1.20

Thanks for your help

**Comment by jcollins-axway** [comment]
This is related to the change we did recently for provisioning an access request. The process creates a product named after the proxy-plan-name and associates that to the app. 

The deprovisioning, for proxy mode, was not updated to format the product name in the same manner with "-plan-name". This will be fixed.

**Comment by jcollins-axway** [comment]
Will be fixed when APIGOV-26363 is merged
