### ISSUE TITLE
Proxy mode - unstructured API services

### ISSUE THREAD

**Issue by gwandwingor** [Axway/agents-apigee#143]
Hi,

In proxy discovery mode, we noticed that proxies with a reference to a spec (association.json) were correctly discovered as "oas" services.
However, it appears that, without altering any of the already discovered proxies/specs, subsequent API service revisions are created with an "unstructured" format as shown below :

![image](https://github.com/Axway/agents-apigee/assets/22820414/3505a630-503d-4d28-a963-72c2ddb16cc2)

**Comment by jcollins-axway** [comment]
This seems to be a logic error. When the call to get the spec file does not fail, but the data returned when getting the spec seems to be bad or empty, we were publishing the API. Will skip publishing in this case.

**Comment by jcollins-axway** [comment]
Will be fixed when APIGOV-26363 is merged
