### ISSUE TITLE
Allow agent to read api specs from local filesystem

### ISSUE THREAD

**Issue by apievangelist-code** [Axway/agents-apigee#183]
Private Apigee have classic Edge which doesn't have feature to store or fetch API-Specs from below mentioned URL.

Agents is failing with http 404 as the URL doesnt exists for private apigee : 

{"component":"httpClient","duration(ms)":2,"id":"60431a0a-6307-47b7-9902-0e949ab976be","level":"trace","message":"request succeeded","method":"GET","package":"sdk.api","received(bytes)":47,"status":404,"time":"2024-01-30T15:47:06+08:00","url":"**_http://{host}:{port}/organizations/{org-name}/specs/folder/home_**"}
{"component":"pollSpecs","error":"invalid character '\u003c' looking for beginning of value","level":"error","message":"getting specs","package":"apigee","time":"2024-01-30T15:47:06+08:00"}
{"component":"baseJob","job-id":"a1431ad5-769e-45f3-a60e-8e7c8ba8f29d","job-name":"Poll Specs","level":"error","message":"[Error Code 1601] - Error in interval job a1431ad5-769e-45f3-a60e-8e7c8ba8f29d execution: invalid character '\u003c' looking for beginning of value","package":"sdk.jobs","time":"2024-01-30T15:47:06+08:00"}

![image](https://github.com/Axway/agents-apigee/assets/28946725/f4d9ffce-49d5-4579-809a-2d7a419cb8c9)

references: 
- https://docs.apigee.com/api-platform/publish/specs/manage-specs#create-api-proxy-from-spec
- https://docs.apigee.com/api-platform/publish/specs/folders

Apparently, API-specs is a mandatory resource for agents to function and integrate successfully, can we allow agent to read/load the api-specs from a local folder ?

**Comment by jcollins-axway** [comment]
local specs directory option now available
