### ISSUE TITLE
DA does not discover proxies with new spec attached

### ISSUE THREAD

**Issue by snon-axway** [Axway/agents-apigee#190]
Hello,

DA agent version 1.1.31
Steps to reproduce:
Publish a new specification "sno3-swagger-specification"
Create a new proxy using the "sno3-swagger-specification"
Publish the proxy

Expected result:
Proxy is discovered and a new service is created on the service registry

Actual result:
Proxy is not discovered. Da needs to be rebooted to have the proxy discovered.

Thanks,
Sovanna

**Comment by snon-axway** [comment]
@jcollins-axway

**Comment by jcollins-axway** [comment]
Fixed in latest release
