### ISSUE TITLE
Traceability agent configuration

### ISSUE THREAD

**Issue by snon-axway** [Axway/agents-apigee#21]
Hello,

Traceability agent should have configuration parameter for :

- traceability enabled: true
- metrics enabled: false

Currently, those are hardcoded in the apigee_traceability_agent.yml file and so hardcoded in the docker image.

Thanks,
Sovanna

**Comment by jcollins-axway** [comment]
@snon-axway maybe there is confusion on these settings.

The traceability.enabled setting referred to must be true for the agent to run, if false is desired then the agent should not be started.

The metrics.enabled setting referred to, I believe, is on line 112 of the yaml. If that is the case than this setting is for beat metrics being added to the log file, the same hardcoding is in all other agents too. I believe you may want the the central metrics on line 22 which doe shave an environment variable.
